domain_path: /home/andy/opt/Xilinx/Projects/FPGA-Course/Lesson10/assignment10_2/vitis/platform_blaze/export/platform_blaze/sw/standalone_microblaze_0
app_src_dir: /home/andy/opt/2026.1/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
